In [1]:
print("Welcome to python for Data Analysis")

Welcome to python for Data Analysis


In [3]:
x=5
if x>4:
    print("True")

# one line comment

True


Functions
- built in 
- library
- custom function
- lambda function

In [6]:
sales = [150,120,160,155,175]

print("total sales :", sum(sales))

avg_sales = sum(sales)/len(sales)

print(f"Average sales = {avg_sales}")

total sales : 760
Average sales = 152.0


In [11]:
import math
print("Ceil:",math.ceil(5.67))
print("floor:",math.floor(5.67))
print("Sqrt:",int(math.sqrt(9)))


Ceil: 6
floor: 5
Sqrt: 3


In [13]:
import statistics

print("Mean:",statistics.mean(sales))
print("Median:",statistics.median(sales))
print("Variance:",statistics.variance(sales))
print("Mode:",statistics.mode(sales))
print("")

Mean: 152
Median: 155
Variance: 407.5
Mode: 150



Custom Functions

In [15]:
def myfun(*args):
    for value in args:
        print(value)


myfun(1,2,3,4.5)

1
2
3
4.5


Keyword Arguments Kwargs

In [16]:
def customer_details(**kwargs):
    for key,value in kwargs.items():
        print(key,value)

customer_details(name = "Rahul", type = "Gold")

name Rahul
type Gold


Lambda functions

lambda x: x**2


In [18]:
lambda x: x**2

<function __main__.<lambda>(x)>

In [25]:
prices = [1000,2000,3000]
discounted_price = list(map(lambda p: p*0.9,prices))
# discounted_price = list(map(lambda p: p*0.9,prices))
print(f"discounted price is {discounted_price}")

discounted price is [900.0, 1800.0, 2700.0]


In [30]:
# Filter transaction > 2000 as high transaction values
transactions = [500,1200,4500,800,3000]

# # without lambda 
# high_transaction = []

# for trans in transactions:
#     if trans>2000:
#         high_transaction.append(trans)

# print(high_transaction)

# # with Lambda

high_transaction = list(filter(lambda t: t>2000, transactions))
high_transaction

[4500, 3000]

In [34]:
customers = {
    "C1":1000,
    "C2":2000,
    "C3":500
}

# sorting(key = lambda x:x[1])
sorted_customers = sorted(customers.items(), key= lambda x: x[1], reverse= True)

print(f"Customers Ranked by Spend: {sorted_customers}")

Customers Ranked by Spend: [('C2', 2000), ('C1', 1000), ('C3', 500)]


In [35]:
def getUsernameStrength(usernames, commonWords):
    
    common = set(commonWords)
    result = []

    for name in usernames:

        if len(name) < 6:
            result.append("weak")
            continue

        if name.isdigit():
            result.append("weak")
            continue

        if name.isupper() or name.islower():
            result.append("weak")
            continue

        if name in common:
            result.append("weak")
            continue

        weak = False

        for i in range(len(name)):
            for j in range(i+1, len(name)+1):
                if name[i:j] in common:
                    weak = True
                    break
            if weak:
                break

        if weak:
            result.append("weak")
        else:
            result.append("strong")

    return result

usernames = "vansh.p"
commonwords = ['vansh','apple', 'banana']

In [36]:
set(commonwords)


{'apple', 'banana', 'vansh'}

In [37]:
len(usernames)


7

In [39]:
for i in range(len(usernames)):
    for j in range(i+1,len(usernames)+1):
        print(i,j)

0 1
0 2
0 3
0 4
0 5
0 6
0 7
1 2
1 3
1 4
1 5
1 6
1 7
2 3
2 4
2 5
2 6
2 7
3 4
3 5
3 6
3 7
4 5
4 6
4 7
5 6
5 7
6 7


In [40]:
usernames[0:1]

'v'

In [41]:
from collections import Counter

def mostFrequent(words):

    count = Counter(words)
    max_freq = max(count.values())

    candidates = [w for w in count if count[w] == max_freq]

    return min(candidates)

In [45]:
seen = set()
seen.add(1)

In [46]:
seen

{1}

In [3]:
def maxSumSubarray(arr, k):

    window_sum = sum(arr[:k])
    max_sum = window_sum

    for i in range(k, len(arr)):
        print(i)

        window_sum += arr[i]
        window_sum -= arr[i-k]

        max_sum = max(max_sum, window_sum)

    return max_sum

In [6]:
arr = [1,9,8,4,5,6,7,2,3]
k = 4

In [7]:
maxSumSubarray(arr,k)

4
5
6
7
8


26

In [5]:
sum(arr[:k])

10

In [8]:
def maxSubArray(nums):

    curr = nums[0]
    best = nums[0]

    for n in nums[1:]:

        curr = max(n, curr+n)
        best = max(best, curr)

    return best

In [9]:
maxSubArray(arr)


45

In [10]:
def longestSubstring(s):
    seen = set()
    left = 0
    ans = 0

    for right in range(len(s)):
        while s[right] in seen:
            seen.remove(s[left])
            left+=1
        seen.add(s[right])
        ans = max(ans, right- left +1)

    return ans , seen

ans = "abcabcabccc"

In [11]:
longestSubstring(ans)

(3, {'c'})

In [16]:
def maxSubArray(nums):

    curr = nums[0]
    best = nums[0]

    for n in nums[1:]:
        print(n)

        curr = max(n, curr+n)
        best = max(best, curr)

    return best

In [13]:
nums = [-2,1,-3,4,-1,2,1,-5,4]

In [17]:
maxSubArray(nums)

1
-3
4
-1
2
1
-5
4


6

In [15]:
nums[0]

-2

In [19]:
arr = [1,9,2,3,6,8]

In [27]:
k = 10

In [ ]:
def faltu(arr,k):
    seen = {}
    for i,n in enumerate(arr):
        x = k-n
        if x in seen:
            return [seen[x],i]
        seen[i] = n
    return None

In [28]:
faltu(arr,k)

[2, 5]

In [1]:
import numpy

In [2]:
sales = numpy.array([1200,1500,900,1800,1600])
print(sales)

[1200 1500  900 1800 1600]


In [4]:
store_sales = numpy.array([
    [1200,1500,900],
    [1800,1600,1700]
])
store_sales

array([[1200, 1500,  900],
       [1800, 1600, 1700]])

In [10]:
# Special Arrays
print(numpy.zeros((2,3))) # gives 2 by 3 null matrix
numpy.ones((2,2))

[[0. 0. 0.]
 [0. 0. 0.]]


array([[1., 1.],
       [1., 1.]])

In [12]:
numpy.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [19]:
numpy.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [20]:
for value in sales:
    print(value)

1200
1500
900
1800
1600


In [ ]:
print("Iterating 2D Array")

for value in store_sales:
    print(value)

Iterating 2D Array
[1200 1500  900]
[1800 1600 1700]


In [22]:
for i in range(2):
    for j in range(3):
        print(store_sales[i,j])

1200
1500
900
1800
1600
1700


Join, split,search, sort And filte

In [35]:
a = numpy.arange(1,4)
b = numpy.arange(4,7)
combined = numpy.concatenate((a,b))
combined

array([1, 2, 3, 4, 5, 6])

Splitting arrays

In [36]:
split_data = numpy.array_split(combined,3)
split_data

[array([1, 2]), array([3, 4]), array([5, 6])]