## Numpy

In [1]:
import numpy

In [4]:
#creating an array
sales = numpy.array([1200, 1500, 900, 1800, 1600])

In [3]:
print(sales)

[1200 1500  900 1800 1600]


In [5]:
store_sales = numpy.array([
                            [1200, 1500, 900], 
                            [1800, 1600, 1700]
                          ])

In [78]:
store_sales.size

6

In [6]:
store_sales

array([[1200, 1500,  900],
       [1800, 1600, 1700]])

In [7]:
print(store_sales)

[[1200 1500  900]
 [1800 1600 1700]]


In [8]:
import numpy as np

In [9]:
a = np.array([[1, 2, 3], [5, 7, 8]])
a

array([[1, 2, 3],
       [5, 7, 8]])

In [12]:
#Special arrays

np.zeros((2, 3))


array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
print("Zero Matrix:", np.zeros((2, 2)))

Zero Matrix: [[0. 0.]
 [0. 0.]]


In [15]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [18]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [19]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [21]:
sales

array([1200, 1500,  900, 1800, 1600])

In [22]:
print("Data Type of sales:", sales.dtype)

Data Type of sales: int64


In [23]:
sales_float = np.array([1200, 1500, 900], dtype = 'float64')
sales_float

array([1200., 1500.,  900.])

In [24]:
b = np.array([3.14, 7.8, 9])
b

array([3.14, 7.8 , 9.  ])

In [26]:
sales_float = sales_float.astype('int32')
sales_float

array([1200, 1500,  900], dtype=int32)

## Indexing & Slicing

In [27]:
# 1d indexing

sales

array([1200, 1500,  900, 1800, 1600])

In [28]:
sales[1]

np.int64(1500)

In [29]:
print("Second Element:", sales[1])

Second Element: 1500


In [30]:
sales[2]

np.int64(900)

In [31]:
sales[1:4]

array([1500,  900, 1800])

In [32]:
sales[1:]

array([1500,  900, 1800, 1600])

In [33]:
sales[3:]

array([1800, 1600])

In [34]:
sales[-1]

np.int64(1600)

In [35]:
# 2d Indexing
store_sales

array([[1200, 1500,  900],
       [1800, 1600, 1700]])

In [36]:
store_sales[1, 1]

np.int64(1600)

In [37]:
store_sales[ : , 1]

array([1500, 1600])

In [38]:
store_sales[1, :]

array([1800, 1600, 1700])

In [39]:
store_sales[:, 1:]

array([[1500,  900],
       [1600, 1700]])

## Shape & Reshape

In [41]:
sales.shape  #1d array

(5,)

In [42]:
print("Shape of sales:", sales.shape)

Shape of sales: (5,)


In [45]:
print("Shape of Store_Sales", store_sales.shape)  #2 d array

Shape of Store_Sales (2, 3)


In [46]:
data = np.array([1, 2, 3, 4, 5, 6])
data

array([1, 2, 3, 4, 5, 6])

In [47]:
data.shape

(6,)

In [48]:
reshaped_data = data.reshape(2, 3)
reshaped_data

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [50]:
reshaped_data.reshape(6)

array([1, 2, 3, 4, 5, 6])

In [52]:
flattened = reshaped_data.reshape(-1)
print("Flattened:", flattened)

Flattened: [1 2 3 4 5 6]


In [53]:
data

array([1, 2, 3, 4, 5, 6])

In [54]:
data.reshape(-1, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

## Iterating Through Arrays

In [55]:
sales

array([1200, 1500,  900, 1800, 1600])

In [56]:
print("Iterating 1D:")

for value in sales:
    print(value)

Iterating 1D:
1200
1500
900
1800
1600


In [57]:
store_sales

array([[1200, 1500,  900],
       [1800, 1600, 1700]])

In [59]:
print("Iterating 2D:")

for row in store_sales:
    print(row)

Iterating 2D:
[1200 1500  900]
[1800 1600 1700]


In [60]:
for i in range(2):
    for j in range(3):
        print(store_sales[i, j])

1200
1500
900
1800
1600
1700


In [61]:
print("Using nditer():")

for element in np.nditer(store_sales):
    print(element)

Using nditer():
1200
1500
900
1800
1600
1700


## Join, Split, Search, Sort & Filter

In [66]:
# joining arrays

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [68]:
combined = np.concatenate((a, b))
print(combined)

[1 2 3 4 5 6]


In [69]:
# splitting arrays
split_data = np.array_split(combined, 3)
split_data

[array([1, 2]), array([3, 4]), array([5, 6])]

In [70]:
split_data = np.array_split(combined, 2)
split_data

[array([1, 2, 3]), array([4, 5, 6])]

In [71]:
# Searching (Boolean Condition)

sales = np.array([1200, 1500, 900, 1800])

indices = np.where(sales > 1400)
print("Indices where sales > 1400:", indices)

Indices where sales > 1400: (array([1, 3]),)


In [72]:
# sorting
sorted_sales = np.sort(sales)
sorted_sales

array([ 900, 1200, 1500, 1800])

In [73]:
#Filtering using Boolean Masking

high_sales = sales[sales>1400]
print("High Sales:", high_sales)

High Sales: [1500 1800]


In [74]:
revenue = np.array([1200, 1500, 1800, 900, 2000, 2200, 1700, 1600, 2500, 3000, 2800, 2600])
revenue

array([1200, 1500, 1800,  900, 2000, 2200, 1700, 1600, 2500, 3000, 2800,
       2600])

In [76]:
#Identify high sales: sales is greater than 2000

high_sales = revenue[revenue > 2000]
high_sales

array([2200, 2500, 3000, 2800, 2600])

In [77]:
#Represent data in quarters

quarterly = revenue.reshape(4, 3)
quarterly

array([[1200, 1500, 1800],
       [ 900, 2000, 2200],
       [1700, 1600, 2500],
       [3000, 2800, 2600]])

In [79]:
quarterly.transpose()

array([[1200,  900, 1700, 3000],
       [1500, 2000, 1600, 2800],
       [1800, 2200, 2500, 2600]])